# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f68689c9d791a56be1b8457c6a88d1a527a9798a4da5c9bb3d144755da0a26b5f29b7f483f4a03c80b16ca8987526a8d19c18f1c170305535288da444072f87

test:
  secret_key_base: 531e8cfae67e179f00eb7a21009d256aaf0e7deb0082b4d45d674ea97c002f6ee7d07701649df9c58a5ca3efd0f0be6fc771857cb9f71334d0a1469a256c1ec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
